version = 1
SPDX-PackageName = "Slang Shading Language VSCode Extension"
SPDX-PackageSupplier = "The Khronos Group, Inc."
SPDX-PackageDownloadLocation = "https://github.com/shader-slang/slang-vscode-extension"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2016, Carnegie Mellon University and NVIDIA Corporation", "2024 The Khronos Group, Inc."]
SPDX-License-Identifier = "Apache-2.0 WITH LLVM-exception"

[[annotations]]
path = ["README.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The Khronos Group, Inc."
SPDX-License-Identifier = "CC-BY-4.0"
